import re

with open("runtime/src/vm.py", "r") as f:
    lines = f.readlines()

new_lines = []
skip = False
for line in lines:
    if "elif op == OpCode.CALL.value:" in line:
        new_lines.append(line)
        new_lines.append("                argc = code[frame.pc + 1]\n")
        new_lines.append("                args = [self._pop() for _ in range(argc)]\n")
        new_lines.append("                args.reverse()\n")
        new_lines.append("                func = self._pop()\n")
        new_lines.append("\n")
        new_lines.append("                if isinstance(func, tuple) and func[0] == 'function':\n")
        new_lines.append("                    func_name = func[1]\n")
        new_lines.append("                    if self.jit_enabled and self.jit:\n")
        new_lines.append("                        self.jit.track_call(func_name)\n")
        new_lines.append("                        if func_name in self.jit.compiled_functions:\n")
        new_lines.append("                            compiled_func = self.jit.compiled_functions[func_name]\n")
        new_lines.append("                            try:\n")
        new_lines.append("                                result = compiled_func.execute(self.globals, *args)\n")
        new_lines.append("                                self._push(result)\n")
        new_lines.append("                                frame.pc += 2\n")
        new_lines.append("                                continue\n")
        new_lines.append("                            except Exception as e:\n")
        new_lines.append("                                trace = self._format_stack_trace()\n")
        new_lines.append('                                raise VMError(f"Internal VM Crash: {e}\\n{trace}")\n')
        new_lines.append("\n")
        new_lines.append("                    func_bc = frame.bytecode.functions.get(func_name)\n")
        new_lines.append("                    if not func_bc: func_bc = self.frames[0].bytecode.functions.get(func_name)\n")
        new_lines.append("                    if func_bc:\n")
        new_lines.append("                        new_frame = CallFrame(func_bc)\n")
        new_lines.append("                        for j in range(min(len(args), func_bc.num_params)):\n")
        new_lines.append("                            if j < len(new_frame.locals): new_frame.locals[j] = args[j]\n")
        new_lines.append("                        if func_bc.varargs_name and func_bc.num_params < len(new_frame.locals):\n")
        new_lines.append("                            new_frame.locals[func_bc.num_params] = list(args[func_bc.num_params:])\n")
        new_lines.append("                        if len(func) == 3:\n")
        new_lines.append("                            closure_env = func[2]\n")
        new_lines.append("                            new_frame.closure_env = closure_env\n")
        new_lines.append("                            for j, name in enumerate(new_frame.bytecode.var_names):\n")
        new_lines.append("                                if name in closure_env:\n")
        new_lines.append("                                    if not isinstance(new_frame.locals[j], Cell): new_frame.locals[j] = Cell(new_frame.locals[j])\n")
        new_lines.append("                                    new_frame.locals[j].value = closure_env[name].value if isinstance(closure_env[name], Cell) else closure_env[name]\n")
        new_lines.append("                        frame.pc += 2\n")
        new_lines.append("                        self.frames.append(new_frame)\n")
        new_lines.append("                        self.current_frame = new_frame\n")
        new_lines.append("                        frame = new_frame\n")
        new_lines.append("                        code = frame.bytecode.code\n")
        new_lines.append("                        constants = frame.bytecode.constants\n")
        new_lines.append("                        frame.pc = 0\n")
        new_lines.append("                        continue\n")
        new_lines.append("                    else: raise VMError(f\"Function not found: {func_name}\")\n")
        new_lines.append("\n")
        new_lines.append("                elif isinstance(func, VakClass):\n")
        new_lines.append("                    instance = VakInstance(func)\n")
        new_lines.append("                    if 'प्रारम्भ' in func.methods:\n")
        new_lines.append("                        func_bc = func.methods['प्रारम्भ']\n")
        new_lines.append("                        new_frame = CallFrame(func_bc, is_constructor=True)\n")
        new_lines.append("                        if len(new_frame.locals) > 0: new_frame.locals[0] = instance\n")
        new_lines.append("                        for j in range(min(len(args), func_bc.num_params)):\n")
        new_lines.append("                            if j + 1 < len(new_frame.locals): new_frame.locals[j+1] = args[j]\n")
        new_lines.append("                        frame.pc += 2\n")
        new_lines.append("                        self.frames.append(new_frame)\n")
        new_lines.append("                        self.current_frame = new_frame\n")
        new_lines.append("                        frame = new_frame\n")
        new_lines.append("                        code = frame.bytecode.code\n")
        new_lines.append("                        constants = frame.bytecode.constants\n")
        new_lines.append("                        frame.pc = 0\n")
        new_lines.append("                        continue\n")
        new_lines.append("                    else:\n")
        new_lines.append("                        self._push(instance)\n")
        new_lines.append("                        frame.pc += 2\n")
        new_lines.append("                        continue\n")
        new_lines.append("\n")
        new_lines.append("                elif isinstance(func, tuple) and func[0] == 'bound_method':\n")
        new_lines.append("                    obj, method_name = func[1], func[2]\n")
        new_lines.append("                    if isinstance(obj, VakInstance):\n")
        new_lines.append("                        func_bc = obj.klass.methods.get(method_name)\n")
        new_lines.append("                        if func_bc:\n")
        new_lines.append("                            new_frame = CallFrame(func_bc)\n")
        new_lines.append("                            if len(new_frame.locals) > 0: new_frame.locals[0] = obj\n")
        new_lines.append("                            for j in range(min(len(args), func_bc.num_params)):\n")
        new_lines.append("                                if j + 1 < len(new_frame.locals): new_frame.locals[j+1] = args[j]\n")
        new_lines.append("                            frame.pc += 2\n")
        new_lines.append("                            self.frames.append(new_frame)\n")
        new_lines.append("                            self.current_frame = new_frame\n")
        new_lines.append("                            frame = new_frame\n")
        new_lines.append("                            code = frame.bytecode.code\n")
        new_lines.append("                            constants = frame.bytecode.constants\n")
        new_lines.append("                            frame.pc = 0\n")
        new_lines.append("                            continue\n")
        new_lines.append("                    raise VMError(f\"Cannot call bound method {method_name}\")\n")
        new_lines.append("\n")
        new_lines.append("                elif callable(func):\n")
        new_lines.append("                    try:\n")
        new_lines.append("                        result = func(*args)\n")
        new_lines.append("                        self._push(result)\n")
        new_lines.append("                        frame.pc += 2\n")
        new_lines.append("                        continue\n")
        new_lines.append("                    except Exception as e: raise VMError(f\"Error calling builtin: {e}\")\n")
        new_lines.append("                else: raise VMError(f\"Object not callable: {type(func).__name__}\")\n")
        
        skip = True
        continue
    
    if skip:
        if "elif op == OpCode." in line and "CALL.value" not in line:
            skip = False
        else:
            continue
    new_lines.append(line)

with open("runtime/src/vm.py", "w") as f:
    f.writelines(new_lines)
