import re

with open("runtime/src/vm.py", "r") as f:
    content = f.read()

# Replace the return { ... } dictionary in _init_builtins
# We will just redefine the entire return statement.

new_return = """        return {
            'पाठ_कर': str,
            'str': str,
            'परास': range,
            'range': range,
            'दीर्घता': len,
            'len': len,
            'प्रकार': _vak_type,
            'type': _vak_type,
            'संख्या': int,
            'int': int,
            'दशमलव': float,
            'float': float,
            'मुद्रय': print,
            'print': print,
            'पठन': _read_file,
            'लेखन': _write_file,
            'अस्तित्व': os.path.exists,
            'मिटाओ': lambda p: os.remove(p) if os.path.exists(p) else None,
            'सूची_निर्देशिका': os.listdir,
            'बनाओ_निर्देशिका': _make_dir,
            'परिवेश_प्राप्त': os.getenv,
            'परिवेश_सेट': os.putenv,
            'प्रणाली_कमांड': os.system,
            'मंच': platform.system,
            'कार्य_निर्देशिका': os.getcwd,
            'संयोग': lambda lst, sep="": sep.join(str(x) for x in lst),
            'विभाजन': lambda s, sep=" ": s.split(sep),
            'छाँटो': lambda s: s.strip(),
            'उच्च': lambda s: s.upper() if isinstance(s, str) else s,
            'निम्न': lambda s: s.lower() if isinstance(s, str) else s,
            'पूर्णांक_कर': int,
            'क्रमबद्ध': sorted,
            'योग': sum,
            'अधिकतम': max,
            'न्यूनतम': min,
            'कुंजियाँ': lambda d: list(d.keys()) if isinstance(d, dict) else [],
            'मान': lambda d: list(d.values()) if isinstance(d, dict) else [],
            'वर्गमूल': math.sqrt,
            '_math_cos': _math_cos,
            '_math_sin': _math_sin,
            '_math_tan': _math_tan,
            '_math_sqrt': _math_sqrt,
            '_math_abs': _math_abs,
            '_math_floor': _math_floor,
            '_math_ceil': _math_ceil,
            '_math_round': _math_round,
            '_math_degrees': _math_degrees,
            '_math_radians': _math_radians,
            'जाल_लाओ': _http_get,
            'जाल_भेजो': _http_post,
            'जाल_डाउनलोड': lambda *args: None, # Dummy if not found
            'जाल_पुट': lambda *args: None,
            'समय': _get_time,
            'निद्रा': _sleep,
            'धागा_शुरू': _start_thread,
            'सेट_टाइमआउट': lambda *args: None,
            'सेट_इंटरवल': lambda *args: None,
            'क्लियर_टाइमआउट': lambda *args: None,
            'async_sleep': lambda *args: None,
            'रेगेक्स_खोज': _re_match,
            'रेगेक्स_बदलो': _re_replace,
            'जेसन_लिखो': _json_encode,
            'जेसन_पढ़ो': _json_decode,
            'परिभाषय': lambda *args: _sansmatic.define(str(args[0]), args[1]),
            'दावा': lambda *args: _sansmatic.assert_fact(str(args[0]), str(args[1]), str(args[2]), str(args[3]) if len(args)>3 else None),
            'नियम': lambda *args: _sansmatic.rule((str(args[0]), str(args[1]), str(args[2])), (str(args[3]), str(args[4]), str(args[5]))),
            'मूल्यांकन': lambda *args: _sansmatic.evaluate(str(args[0]), str(args[1]), str(args[2])),
            'सिद्ध_है': lambda *args: _sansmatic.is_provable(str(args[0]), str(args[1]), str(args[2])),
            'आत्म_मूल्य': _atma_wrap,
            'भाव_पढ़ो': lambda *args: _atmalipi.read_bhav(str(args[0])),
            'अवस्था_पढ़ो': lambda *args: _atmalipi.read_avastha(str(args[0])),
            'सभी_भाव': lambda *args: [f"{k} → {v}" for k, v in _atmalipi.all_bhav().items()],
            'सभी_अवस्था': lambda *args: [f"{k} → {v}" for k, v in _atmalipi.all_avastha().items()],
            'आत्म_इतिहास': lambda *args: _atmalipi.get_history(),
            'आत्म_है': lambda *args: isinstance(args[0], AtmaValue) if args else False,
            'आत्म_भाव': lambda *args: args[0].bhav or "शून्य" if args and isinstance(args[0], AtmaValue) else "शून्य",
            'आत्म_अवस्था': lambda *args: args[0].avastha or "शून्य" if args and isinstance(args[0], AtmaValue) else "शून्य",
            'आत्म_मूल': lambda *args: args[0].value if args and isinstance(args[0], AtmaValue) else (args[0] if args else None),
            '_chitra_canvas': lambda *args: _chitra_canvas_impl(*args),
            '_chitra_fill': lambda *args: _chitra_fill_impl(*args),
            '_chitra_point': lambda *args: _chitra_point_impl(*args),
            '_chitra_line': lambda *args: _chitra_line_impl(*args),
            '_chitra_circle': lambda *args: _chitra_circle_impl(*args),
            '_chitra_rect': lambda *args: _chitra_rect_impl(*args),
            '_chitra_polygon': lambda *args: _chitra_polygon_impl(*args),
            '_chitra_text': lambda *args: _chitra_text_impl(*args),
            '_chitra_save': lambda *args: _chitra_save_impl(*args),
            '_chitra_load': lambda *args: _chitra_load_impl(*args),
            '_chitra_color': lambda *args: _chitra_color_impl(*args),
            '_chitra_colors': lambda *args: _chitra_colors_impl(*args),
            '_chitra_width': lambda *args: _chitra_width_impl(*args),
            '_chitra_height': lambda *args: _chitra_height_impl(*args),
            '_chitra_pixel_get': lambda *args: _chitra_pixel_get_impl(*args),
            '_chitra_pixel_set': lambda *args: _chitra_pixel_set_impl(*args),
            '_chitra_clear': lambda *args: None,
            '_chitra_text_centered': lambda *args: None,
            '_chitra_gradient': lambda *args: None,
            '_chitra_rotate': lambda *args: None,
            '_chitra_mandala': lambda *args: None,
            '_chitra_kaleidoscope': lambda *args: None,
            'पायथन_आयात': पायथन_आयात,
            'पायथन_चलाओ': पायथन_चलाओ,
            'पायथन_मूल्यांकन': पायथन_मूल्यांकन,
            'अक्षर_मान': ord,
        }"""

pattern = r'return \{\n\s+\'पाठ_कर\': str,.*?\n\s+\}'
content = re.sub(pattern, new_return, content, flags=re.DOTALL)

with open("runtime/src/vm.py", "w") as f:
    f.write(content)
